use std::env;
use std::path;

fn main() {
  let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

  cbindgen::Builder::new()
    .with_crate(crate_dir)
    .with_language(cbindgen::Language::Cxx)
    .with_autogen_warning("/* Autogenerated by cbindgen in build.rs. Do not edit. */\n\n#pragma once")
    .generate()
    .expect("Unable to generate bindings")
    .write_to_file(path::PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("bindings.h"));
}
